using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.Experimental.Rendering;
using UnityEngine.TextCore.LowLevel;
using Object = UnityEngine.Object;

namespace MieMieFrameWork.Localization.FontManagement
{
    public sealed class FontCoverage
    {
        public readonly HashSet<uint> unsupported = new HashSet<uint>();
        public readonly HashSet<uint> unbaked = new HashSet<uint>();
        public bool sourceUnavailable;
        public string sourceUnavailableName;
        // The glyph can be generated by a Dynamic TMP asset, but the current
        // atlas has not been checked for capacity yet.
        public readonly HashSet<uint> dynamicPending = new HashSet<uint>();
        // A character can be absent from the primary font and still be valid
        // because a fallback asset already contains it (or can generate it).
        public readonly Dictionary<uint, TMP_FontAsset> resolvedByFallback = new Dictionary<uint, TMP_FontAsset>();
    }

    public sealed class FontAtlasInspection
    {
        public Texture2D texture;
        public string assetPath;
        public int width;
        public int height;
        public long alpha8Bytes;
        public string format;
        public bool readable;
        public int mipCount;
        public long estimatedAtlasBytes;
    }

    public sealed class FontAssetInspection
    {
        public TMP_FontAsset asset;
        public string assetPath;
        public Font sourceFont;
        public string sourceFontPath;
        public AtlasPopulationMode populationMode;
        public bool multiAtlas;
        public Material material;
        public string materialPath;
        public int characterCount;
        public int glyphCount;
        public long estimatedAtlasBytes;
        public bool requiresRuntimeSource;
        public readonly List<FontAtlasInspection> atlases = new List<FontAtlasInspection>();
        public readonly List<TMP_FontAsset> fallbacks = new List<TMP_FontAsset>();
    }

    public static class FontBakeService
    {
        public static string LastBackupPath { get; private set; }
        public static Font GetReferencedSourceFont(TMP_FontAsset asset)
        {
            if (asset == null) return null;
            if (asset.sourceFontFile != null) return asset.sourceFontFile;
#if UNITY_EDITOR
            // Static TMP assets clear sourceFontFile at runtime, but Unity TMP
            // keeps the editor-only reference so the asset can be inspected or
            // switched back to Dynamic later.
            var serialized = new SerializedObject(asset);
            var property = serialized.FindProperty("m_SourceFontFile_EditorRef");
            var editorFont = property == null ? null : property.objectReferenceValue as Font;
            if (editorFont != null) return editorFont;
            var guidProperty = serialized.FindProperty("m_SourceFontFileGUID");
            string guid = guidProperty == null ? asset.creationSettings.sourceFontFileGUID : guidProperty.stringValue;
            if (string.IsNullOrEmpty(guid)) guid = asset.creationSettings.sourceFontFileGUID;
            if (!string.IsNullOrEmpty(guid)) return AssetDatabase.LoadAssetAtPath<Font>(AssetDatabase.GUIDToAssetPath(guid));
            return null;
#else
            return null;
#endif
        }

        public static bool HasGlyph(Font font, uint code)
        {
            if (font == null) return false;
            FontEngine.InitializeFontEngine();
            if (FontEngine.LoadFontFace(font, 64) != FontEngineError.Success) return false;
            return FontEngine.TryGetGlyphWithUnicodeValue(code, GlyphLoadFlags.LOAD_NO_BITMAP, out var glyph) && glyph.index != 0;
        }

        public static IReadOnlyList<TMP_FontAsset> GetGlobalFallbacks()
        {
            var result = new List<TMP_FontAsset>();
            if (TMP_Settings.fallbackFontAssets != null) result.AddRange(TMP_Settings.fallbackFontAssets.Where(f => f != null));
            if (TMP_Settings.defaultFontAsset != null && !result.Contains(TMP_Settings.defaultFontAsset)) result.Add(TMP_Settings.defaultFontAsset);
            return result;
        }

        public static FontAssetInspection Inspect(TMP_FontAsset asset)
        {
            if (asset == null) return null;
            var result = new FontAssetInspection
            {
                asset = asset,
                assetPath = AssetDatabase.GetAssetPath(asset),
                sourceFont = GetReferencedSourceFont(asset),
                populationMode = asset.atlasPopulationMode,
                multiAtlas = asset.isMultiAtlasTexturesEnabled,
                material = asset.material,
                materialPath = asset.material == null ? string.Empty : AssetDatabase.GetAssetPath(asset.material),
                characterCount = asset.characterTable == null ? 0 : asset.characterTable.Count,
                glyphCount = asset.glyphTable == null ? 0 : asset.glyphTable.Count,
                requiresRuntimeSource = asset.atlasPopulationMode == AtlasPopulationMode.Dynamic
            };
            result.sourceFontPath = result.sourceFont == null ? string.Empty : AssetDatabase.GetAssetPath(result.sourceFont);
            if (asset.fallbackFontAssetTable != null) result.fallbacks.AddRange(asset.fallbackFontAssetTable.Where(f => f != null));
            foreach (var texture in asset.atlasTextures ?? Array.Empty<Texture2D>())
            {
                if (texture == null) continue;
                result.atlases.Add(new FontAtlasInspection
                {
                    texture = texture,
                    assetPath = AssetDatabase.GetAssetPath(texture),
                    width = texture.width,
                    height = texture.height,
                    alpha8Bytes = (long)texture.width * texture.height,
                    format = texture.graphicsFormat.ToString(),
                    readable = texture.isReadable,
                    mipCount = texture.mipmapCount,
                    estimatedAtlasBytes = EstimateTextureBytes(texture)
                });
            }
            result.estimatedAtlasBytes = result.atlases.Sum(a => a.estimatedAtlasBytes);
            return result;
        }

        static long EstimateTextureBytes(Texture2D texture)
        {
            if (texture == null) return 0;
            try
            {
                return GraphicsFormatUtility.ComputeMipChainSize(texture.width, texture.height, texture.graphicsFormat, texture.mipmapCount);
            }
            catch
            {
                // Some imported formats cannot be queried until the asset is
                // loaded by the graphics backend. Keep a conservative fallback.
                return (long)texture.width * texture.height * Math.Max(1, texture.mipmapCount == 0 ? 1 : 2);
            }
        }

        public static long EstimateAtlasBytes(TMP_FontAsset asset)
        {
            var info = Inspect(asset);
            return info == null ? 0 : info.estimatedAtlasBytes;
        }

        public static string FormatBytes(long bytes)
        {
            if (bytes < 1024) return bytes + " B";
            if (bytes < 1024 * 1024) return (bytes / 1024f).ToString("0.##") + " KiB";
            return (bytes / 1048576f).ToString("0.##") + " MiB";
        }

        public static string DescribeAsset(TMP_FontAsset asset)
        {
            var info = Inspect(asset);
            if (info == null) return "未选择 TMP Font Asset。";
            string source = info.sourceFont == null ? "未记录源 TTF" : info.sourceFont.name + "（" + info.sourceFontPath + "）";
            string atlas = info.atlases.Count == 0 ? "无图集" : info.atlases.Count + " 张图集：" + string.Join("、", info.atlases.Select(a => a.texture.name + "（" + a.width + "×" + a.height + "，" + a.format + "，" + FormatBytes(a.estimatedAtlasBytes) + "，" + a.assetPath + "）"));
            string fallback = info.fallbacks.Count == 0 ? "无 fallback" : "fallback：" + string.Join("、", info.fallbacks.Select(f => f.name));
            return "源 TTF：" + source + " · " + (info.populationMode == AtlasPopulationMode.Dynamic ? "动态" : "静态") + " · " + fallback + " · " + atlas + " · 材质：" + (info.material == null ? "无" : info.material.name);
        }

        public static FontCoverage Check(Font font, uint[] codes, TMP_FontAsset baked)
        {
            return Check(font, codes, baked, null);
        }

        public static FontCoverage Check(Font font, uint[] codes, TMP_FontAsset baked, IEnumerable<TMP_FontAsset> fallbackFonts)
        {
            var result = new FontCoverage();
            var values = (codes ?? Array.Empty<uint>()).Distinct().ToArray();
            var explicitFallbacks = fallbackFonts ?? Enumerable.Empty<TMP_FontAsset>();
            var globalFallbacks = baked == null ? Enumerable.Empty<TMP_FontAsset>() : GetGlobalFallbacks();
            var localFallbacks = baked == null ? Enumerable.Empty<TMP_FontAsset>() : baked.fallbackFontAssetTable ?? Enumerable.Empty<TMP_FontAsset>();
            var fallbacks = EnumerateFallbacks(explicitFallbacks.Concat(localFallbacks).Concat(globalFallbacks), baked).ToArray();
            var primaryHasGlyph = new Dictionary<uint, bool>();
            var primarySource = font ?? GetReferencedSourceFont(baked);
            bool needsPrimarySource = primarySource != null && values.Any(code => baked == null || !baked.characterLookupTable.ContainsKey(code));
            if (needsPrimarySource)
            {
                FontEngine.InitializeFontEngine();
                if (FontEngine.LoadFontFace(primarySource, 64) == FontEngineError.Success)
                {
                    foreach (uint code in values)
                        primaryHasGlyph[code] = FontEngine.TryGetGlyphWithUnicodeValue(code, GlyphLoadFlags.LOAD_NO_BITMAP, out var glyph) && glyph.index != 0;
                }
                else
                {
                    // A static TMP can still be completely usable when its
                    // editor source reference is present but the font data is
                    // unavailable. Keep the baked/fallback results and mark
                    // only the unresolved characters as unsupported.
                    result.sourceUnavailable = true;
                    result.sourceUnavailableName = primarySource.name;
                }
            }
            foreach (uint code in values)
            {
                bool bakedHasGlyph = baked != null && baked.characterLookupTable.ContainsKey(code);
                bool primaryHas = primarySource != null && primaryHasGlyph.TryGetValue(code, out var has) && has;
                if (bakedHasGlyph) continue;
                if (baked != null && baked.atlasPopulationMode == AtlasPopulationMode.Dynamic && primaryHas)
                {
                    result.dynamicPending.Add(code);
                    continue;
                }
                TMP_FontAsset provider = null;
                bool dynamic = false;
                foreach (var fallback in fallbacks)
                {
                    if (fallback.characterLookupTable != null && fallback.characterLookupTable.ContainsKey(code)) { provider = fallback; break; }
                    if (fallback.atlasPopulationMode == AtlasPopulationMode.Dynamic && HasGlyph(GetReferencedSourceFont(fallback), code)) { provider = fallback; dynamic = true; break; }
                }
                if (provider != null)
                {
                    result.resolvedByFallback[code] = provider;
                    if (dynamic) result.dynamicPending.Add(code);
                }
                else if (primaryHas) result.unbaked.Add(code);
                else result.unsupported.Add(code);
            }
            return result;
        }

        public static bool CoversCharacter(TMP_FontAsset root, uint code)
        {
            if (root == null) return false;
            if (root.characterLookupTable != null && root.characterLookupTable.ContainsKey(code)) return true;
            if (root.atlasPopulationMode == AtlasPopulationMode.Dynamic && HasGlyph(GetReferencedSourceFont(root), code)) return true;
            foreach (var fallback in EnumerateFallbacks((root.fallbackFontAssetTable ?? Enumerable.Empty<TMP_FontAsset>()).Concat(GetGlobalFallbacks()), root))
            {
                if (fallback.characterLookupTable != null && fallback.characterLookupTable.ContainsKey(code)) return true;
                if (fallback.atlasPopulationMode == AtlasPopulationMode.Dynamic && HasGlyph(GetReferencedSourceFont(fallback), code)) return true;
            }
            return false;
        }

        static IEnumerable<TMP_FontAsset> EnumerateFallbacks(IEnumerable<TMP_FontAsset> roots, TMP_FontAsset baked)
        {
            var seen = new HashSet<TMP_FontAsset>();
            if (baked != null) seen.Add(baked);
            var list = roots ?? Enumerable.Empty<TMP_FontAsset>();
            var stack = new Stack<TMP_FontAsset>(list.Where(f => f != null).Reverse());
            while (stack.Count > 0)
            {
                var current = stack.Pop();
                if (current == null || current == baked || !seen.Add(current)) continue;
                yield return current;
                if (current.fallbackFontAssetTable == null) continue;
                foreach (var nested in current.fallbackFontAssetTable.AsEnumerable().Reverse()) if (nested != null) stack.Push(nested);
            }
        }

        public static string Signature(FontBakeProfile profile, uint[] codes)
        {
            string path = AssetDatabase.GetAssetPath(profile.sourceFont);
            string fallbacks = string.Join(",", (profile.fallbackFontAssets ?? new List<TMP_FontAsset>()).Where(f => f != null).Select(f => AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(f))));
            return Hash128.Compute(path + "|" + AssetDatabase.GetAssetDependencyHash(path) + "|" + profile.samplingSize + "|" + profile.padding + "|" + profile.atlasSize + "|" + profile.renderMode + "|" + profile.populationMode + "|" + profile.enableMultiAtlas + "|" + fallbacks + "|" + string.Join(",", codes)).ToString();
        }

        public static TMP_FontAsset BuildTransient(Font source, uint[] codes, int size, int padding, int atlas, GlyphRenderMode mode)
        {
            return BuildTransient(source, codes, size, padding, atlas, mode, AtlasPopulationMode.Static, false, null);
        }

        public static TMP_FontAsset BuildTransient(Font source, uint[] codes, int size, int padding, int atlas, GlyphRenderMode mode, AtlasPopulationMode populationMode, bool enableMultiAtlas, IEnumerable<TMP_FontAsset> fallbackFonts)
        {
            if (source == null || codes.Length == 0) throw new InvalidOperationException("请选择字体并提供至少一个可显示字符。");
            if (size < 16 || size > 200 || padding < 1 || padding > 32 || !new[] { 512, 1024, 2048, 4096 }.Contains(atlas)) throw new ArgumentException("烘焙参数超出支持范围。");
            if (mode != GlyphRenderMode.SDFAA && mode != GlyphRenderMode.SDF && mode != GlyphRenderMode.SDF8 && mode != GlyphRenderMode.SDF16 && mode != GlyphRenderMode.SDF32) throw new ArgumentException("第一版支持 SDF 系列渲染模式。");
            var coverage = Check(source, codes, null, fallbackFonts);
            if (coverage.sourceUnavailable) throw new InvalidOperationException("无法读取源字体“" + source.name + "”，请检查 Include Font Data 或恢复源文件后再补齐字形。");
            if (coverage.unsupported.Count > 0) throw new InvalidOperationException("源字体“" + source.name + "”不包含 " + coverage.unsupported.Count + " 个字形，例如：" + DescribeShort(coverage.unsupported) + "。请在缺失补齐中定位来源，并补充包含字形的 fallback TMP；增大图集不能生成源字体没有的字形。");
            // Pack every glyph supported by the selected source, even if a
            // fallback also contains it. That preserves the selected typeface.
            FontEngine.InitializeFontEngine();
            if (FontEngine.LoadFontFace(source, size) != FontEngineError.Success) throw new InvalidOperationException("无法读取源字体：" + source.name);
            var bakeCodes = codes.Where(c => FontEngine.TryGetGlyphWithUnicodeValue(c, GlyphLoadFlags.LOAD_NO_BITMAP, out var glyph) && glyph.index != 0).Distinct().ToArray();
            TMP_FontAsset font = null;
            try
            {
                // TMP requires Dynamic while characters are added. Static is
                // applied only after the requested set has been packed.
                font = TMP_FontAsset.CreateFontAsset(source, size, padding, mode, atlas, atlas, AtlasPopulationMode.Dynamic, enableMultiAtlas);
                if (font == null) throw new InvalidOperationException("TMP 无法读取字体，请检查 Include Font Data。");
                if (bakeCodes.Length > 0 && !font.TryAddCharacters(bakeCodes, out uint[] missing, true)) throw new InvalidOperationException("图集无法容纳全部字符（" + (missing?.Length ?? 0) + " 个未烘焙）。请增大图集、降低采样字号，或减少字符。");
                font.fallbackFontAssetTable = (fallbackFonts ?? Enumerable.Empty<TMP_FontAsset>()).Where(f => f != null && f != font).Distinct().ToList();
                font.atlasPopulationMode = populationMode;
                var shader = Shader.Find("TextMeshPro/Distance Field");
                if (shader == null) throw new InvalidOperationException("缺少 TMP Distance Field Shader，请导入 TMP Essential Resources。");
                font.material.shader = shader;
                font.name = source.name + (populationMode == AtlasPopulationMode.Dynamic ? " Dynamic" : " SDF");
                var usedAtlases = (font.atlasTextures ?? Array.Empty<Texture2D>()).Where(t => t != null).ToArray();
                font.atlasTextures = usedAtlases;
                for (int i = 0; i < usedAtlases.Length; i++) usedAtlases[i].name = font.name + " Atlas" + (i == 0 ? string.Empty : " " + (i + 1));
                font.material.name = font.name + " Material";
                return font;
            }
            catch { DestroyTransient(font); throw; }
        }

        public static string Describe(IEnumerable<uint> codes) => string.Join(" ", codes.Take(20).Select(c => char.ConvertFromUtf32((int)c) + " U+" + c.ToString("X4")));

        public static string DescribeShort(IEnumerable<uint> codes, int take = 8)
        {
            var values = codes.Distinct().ToArray();
            string sample = string.Join(" ", values.Take(take).Select(c => char.ConvertFromUtf32((int)c)));
            return values.Length <= take ? sample : sample + " …（共 " + values.Length + " 个）";
        }

        public static void DestroyTransient(TMP_FontAsset font)
        {
            if (font == null || EditorUtility.IsPersistent(font)) return;
            foreach (var texture in font.atlasTextures ?? Array.Empty<Texture2D>()) if (texture != null && !EditorUtility.IsPersistent(texture)) Object.DestroyImmediate(texture);
            if (font.material != null && !EditorUtility.IsPersistent(font.material)) Object.DestroyImmediate(font.material);
            Object.DestroyImmediate(font);
        }

        public static TMP_FontAsset Bake(FontBakeProfile profile, FontCharacterSet set)
        {
            // Complete all packing and validation before touching persistent resources.
            var staged = BuildTransient(profile.sourceFont, set.Codes, profile.samplingSize, profile.padding, profile.atlasSize, profile.renderMode, profile.populationMode, profile.enableMultiAtlas, profile.fallbackFontAssets);
            try
            {
                return PersistCandidate(profile, staged, set.Codes, true);
            }
            finally { DestroyTransient(staged); }
        }

        public static bool CanUpdateInPlace(TMP_FontAsset target, TMP_FontAsset staged, out string reason)
        {
            reason = string.Empty;
            if (target == null) { reason = "还没有现有 TMP 资源。"; return false; }
            if (staged == null) { reason = "候选 TMP 资源为空。"; return false; }
            string path = AssetDatabase.GetAssetPath(target);
            var targetTextures = (target.atlasTextures ?? Array.Empty<Texture2D>()).ToArray();
            var stagedTextures = (staged.atlasTextures ?? Array.Empty<Texture2D>()).ToArray();
            if (!path.StartsWith("Assets/", StringComparison.Ordinal)) { reason = "目标 TMP 不在可编辑的 Assets 目录中。"; return false; }
            if (targetTextures.Length == 0 || targetTextures.Any(t => t == null || AssetDatabase.GetAssetPath(t) != path)) { reason = "目标 TMP 缺少同文件内的图集子资源。"; return false; }
            if (target.material == null || AssetDatabase.GetAssetPath(target.material) != path) { reason = "目标 TMP 缺少同文件内的材质子资源。"; return false; }
            if (targetTextures.Length != stagedTextures.Length) { reason = "图集数量从 " + targetTextures.Length + " 变为 " + stagedTextures.Length + "，为保护现有引用需要另存新的 TMP。"; return false; }
            return true;
        }

        /// <summary>
        /// Persists a fully validated transient candidate. Existing assets are
        /// updated only when all sub-resource counts match, preserving local IDs.
        /// In-place writes fail when the atlas count changes. A caller must
        /// explicitly choose updateExisting=false to save a separate asset.
        /// </summary>
        public static TMP_FontAsset PersistCandidate(FontBakeProfile profile, TMP_FontAsset staged, uint[] codes, bool updateExisting)
        {
            if (profile == null) throw new ArgumentNullException(nameof(profile));
            if (staged == null) throw new ArgumentNullException(nameof(staged));
            LastBackupPath = null;
            EnsureFolders();
            TMP_FontAsset result = profile.generatedFont;
            if (updateExisting && result != null)
            {
                if (!CanUpdateInPlace(result, staged, out string reason))
                    throw new InvalidOperationException(reason + " 请调整烘焙参数保持图集数量不变，或明确创建新的 TMP 配置。");
                result = UpdateInPlace(result, staged, profile.fallbackFontAssets);
            }
            else
            {
                string suffix = result == null ? string.Empty : "_" + DateTime.Now.ToString("yyyyMMdd_HHmmss");
                string path = AssetDatabase.GenerateUniqueAssetPath(FontManagerPaths.Generated + "/" + SafeName(profile.sourceFont.name + "_" + profile.locale + "_" + profile.usage + suffix) + ".asset");
                try
                {
                    AssetDatabase.CreateAsset(staged, path);
                    foreach (var texture in staged.atlasTextures ?? Array.Empty<Texture2D>())
                        if (texture != null) AssetDatabase.AddObjectToAsset(texture, staged);
                    if (staged.material != null) AssetDatabase.AddObjectToAsset(staged.material, staged);
                    AssetDatabase.SaveAssetIfDirty(staged);
                    result = staged;
                }
                catch { AssetDatabase.DeleteAsset(path); throw; }
            }
            profile.generatedFont = result;
            profile.lastBakeSignature = Signature(profile, codes ?? Array.Empty<uint>());
            profile.lastBakedSourceFontGuid = AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(profile.sourceFont));
            int atlasCount = result.atlasTextures == null ? 0 : result.atlasTextures.Length;
            profile.lastBakeSummary = (codes == null ? 0 : codes.Length) + " 个字符 · " + (profile.populationMode == AtlasPopulationMode.Dynamic ? "动态" : "静态") + " · " + atlasCount + " 张图集 · " + profile.atlasSize + " × " + profile.atlasSize + " · 纹理基础内存约 " + (profile.atlasSize * profile.atlasSize * Math.Max(1, atlasCount) / 1048576f).ToString("0.##") + " MiB（Alpha8，无 Mipmap）";
            EditorUtility.SetDirty(profile); AssetDatabase.SaveAssetIfDirty(profile);
            return result;
        }

        static TMP_FontAsset UpdateInPlace(TMP_FontAsset target, TMP_FontAsset staged, IEnumerable<TMP_FontAsset> fallbackFonts)
        {
            if (!CanUpdateInPlace(target, staged, out string reason)) throw new InvalidOperationException(reason);
            var targetTextures = target.atlasTextures ?? Array.Empty<Texture2D>();
            var stagedTextures = staged.atlasTextures ?? Array.Empty<Texture2D>();
            var material = target.material;
            var path = AssetDatabase.GetAssetPath(target);
            EnsureFolders();
            LastBackupPath = AssetDatabase.GenerateUniqueAssetPath(FontManagerPaths.Backups + "/" + SafeName(target.name) + "_" + DateTime.Now.ToString("yyyyMMdd_HHmmss") + ".asset");
            AssetDatabase.SaveAssetIfDirty(target);
            if (!AssetDatabase.CopyAsset(path, LastBackupPath)) throw new InvalidOperationException("无法创建更新前备份：" + LastBackupPath);
            // CopyAsset refreshes the database and can invalidate managed
            // references to the original object. Reload all sub-assets before
            // taking the in-memory rollback snapshots.
            target = AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(path);
            if (target == null) throw new InvalidOperationException("更新前重新加载 TMP 资源失败：" + path);
            targetTextures = (target.atlasTextures ?? Array.Empty<Texture2D>()).ToArray();
            material = target.material;
            var texture = targetTextures[0];
            var fontBackup = Object.Instantiate(target);
            var textureBackups = targetTextures.Select(Object.Instantiate).ToArray();
            var materialBackup = Object.Instantiate(material);
            fontBackup.name = target.name;
            for (int i = 0; i < targetTextures.Length; i++) textureBackups[i].name = targetTextures[i].name;
            materialBackup.name = material.name;
            try
            {
                for (int i = 0; i < targetTextures.Length; i++) EditorUtility.CopySerialized(stagedTextures[i], targetTextures[i]);
                EditorUtility.CopySerialized(staged.material, material);
                material.mainTexture = texture;
                // Preserve font, texture and material local IDs so existing UI/presets survive updates.
                EditorUtility.CopySerialized(staged, target);
                target.name = fontBackup.name;
                target.atlasTextures = targetTextures; target.material = material;
                target.fallbackFontAssetTable = (fallbackFonts ?? Enumerable.Empty<TMP_FontAsset>()).Where(f => f != null && f != target).Distinct().ToList();
                target.normalStyle = fontBackup.normalStyle; target.normalSpacingOffset = fontBackup.normalSpacingOffset;
                target.boldStyle = fontBackup.boldStyle; target.boldSpacing = fontBackup.boldSpacing;
                target.italicStyle = fontBackup.italicStyle; target.tabSize = fontBackup.tabSize;
                var sourceSerialized = new SerializedObject(fontBackup);
                var targetSerialized = new SerializedObject(target);
                var atlasProperty = targetSerialized.FindProperty("m_AtlasTexture");
                if (atlasProperty != null) atlasProperty.objectReferenceValue = texture;
                var atlasesProperty = targetSerialized.FindProperty("m_AtlasTextures");
                if (atlasesProperty != null)
                {
                    atlasesProperty.arraySize = targetTextures.Length;
                    for (int i = 0; i < targetTextures.Length; i++) atlasesProperty.GetArrayElementAtIndex(i).objectReferenceValue = targetTextures[i];
                }
                var weightProperty = sourceSerialized.FindProperty("m_FontWeightTable");
                if (weightProperty != null) targetSerialized.CopyFromSerializedProperty(weightProperty);
                targetSerialized.ApplyModifiedPropertiesWithoutUndo();
                target.ReadFontAssetDefinition();
                foreach (var targetTexture in targetTextures) EditorUtility.SetDirty(targetTexture);
                EditorUtility.SetDirty(material); EditorUtility.SetDirty(target);
                AssetDatabase.SaveAssetIfDirty(target);
            }
            catch
            {
                for (int i = 0; i < targetTextures.Length; i++)
                    if (textureBackups[i] != null && targetTextures[i] != null) EditorUtility.CopySerialized(textureBackups[i], targetTextures[i]);
                if (materialBackup != null && material != null) EditorUtility.CopySerialized(materialBackup, material);
                if (fontBackup != null && target != null) EditorUtility.CopySerialized(fontBackup, target);
                if (target != null) target.ReadFontAssetDefinition();
                foreach (var targetTexture in targetTextures) if (targetTexture != null) EditorUtility.SetDirty(targetTexture);
                if (material != null) EditorUtility.SetDirty(material);
                if (target != null) { EditorUtility.SetDirty(target); AssetDatabase.SaveAssetIfDirty(target); }
                throw;
            }
            finally
            {
                if (fontBackup != null) Object.DestroyImmediate(fontBackup);
                foreach (var textureBackup in textureBackups)
                    if (textureBackup != null) Object.DestroyImmediate(textureBackup);
                if (materialBackup != null) Object.DestroyImmediate(materialBackup);
            }
            return target;
        }

        public static void EnsureFolders()
        {
            if (!AssetDatabase.IsValidFolder(FontManagerPaths.Root)) AssetDatabase.CreateFolder("Assets/MieMieFrameTools/ADefaultRes", "Fonts");
            foreach (string name in new[] { "Profiles", "Generated", "Backups" }) if (!AssetDatabase.IsValidFolder(FontManagerPaths.Root + "/" + name)) AssetDatabase.CreateFolder(FontManagerPaths.Root, name);
        }

        public static string SafeName(string name)
        {
            foreach (var c in Path.GetInvalidFileNameChars()) name = name.Replace(c, '_');
            return string.IsNullOrWhiteSpace(name) ? "Font" : name;
        }
    }
}
